### ISSUE TITLE
[Dapp UI] Final improvements

### ISSUE THREAD

**Issue by artyomignatyev** [VolcaTech/cryptoxmas.xyz#106]
All figma frames under pink background: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Crypto-Xmas?node-id=1104%3A271

Marked all changes with pink rectangles above changed things + text with comments under frames.

Added screens with Gifts history.

**Comment by sashamihaha** [comment]
improved in https://github.com/VolcaTech/cryptoxmas.xyz/pull/109

**Comment by seichris** [comment]
good job Sascha! Two things we need need to fix:

- the gray rarity labels? can u verify @artyomignatyev ?
- typo in the send&buy screen "Add pesonal message & ETH for your friend" -> pesonal needs an 'r'

**Comment by artyomignatyev** [comment]
@seichris yep, gray cc/ @sashamihaha
