### ISSUE TITLE
[Dapp UI] add description for unique tokens

### ISSUE THREAD

**Issue by seichris** [VolcaTech/cryptoxmas.xyz#110]
Right now, a user cannot see a unique token's attributes. E.g. The token holder getting a merchandise mug. Proposed two possible fixes in figma. 

[see Artyom's final screens in figma]

Additionally we could show the text on the index already, if you click the card?! What do you think @artyomignatyev

**Comment by artyomignatyev** [comment]
Updated: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Crypto-Xmas?node-id=1154%3A1836

**Comment by sashamihaha** [comment]
implemented in https://github.com/VolcaTech/cryptoxmas.xyz/pull/113
