### ISSUE TITLE
Add other wallets support on Mobile 

### ISSUE THREAD

**Issue by Dobrokhvalov** [VolcaTech/cryptoxmas.xyz#30]
@artyomignatyev please update Figma designs accordingly and forward this issue to @sashamihaha 

![2018-12-04 12 39 28](https://user-images.githubusercontent.com/4770810/49432866-ab54a480-f7c1-11e8-9642-82606207d292.jpg)
![2018-12-04 12 39 20](https://user-images.githubusercontent.com/4770810/49432868-ab54a480-f7c1-11e8-8cbd-e73cbafd029d.jpg)

**Comment by sashamihaha** [comment]
fixed in - https://github.com/VolcaTech/cryptoxmas.xyz/pull/40
