### ISSUE TITLE
[UX] Loading page should guide to sign in Metamask

### ISSUE THREAD

**Issue by seichris** [VolcaTech/cryptoxmas.xyz#33]
### Problem

(Metamask is installed & unlocked. But not signed in.)

On first load, the site only shows me this loading circle, without guiding me to check my Metamask. 

![49403903-3eec8d80-f74e-11e8-9524-3b403967a20e](https://user-images.githubusercontent.com/25006584/49433984-7e00fa00-f7b3-11e8-95b4-ae1fa7ec1047.jpg)

### Proposed solution

The screen should tell me to open my Metamask.

### Prioritization

Very nice UX update. Not much work.

**Comment by seichris** [comment]
Its the same problem with the eth2.io site.

Are you happy with this solution?

![untitled-1](https://user-images.githubusercontent.com/25006584/49434850-7a6e7280-f7b5-11e8-8b31-0b595b735eea.jpg)

**Comment by artyomignatyev** [comment]
Glad you noticed, good proposed solution cc/ @sashamihaha need to fix this
