### ISSUE TITLE
Another list of webapp UI minor bugs

### ISSUE THREAD

**Issue by artyomignatyev** [VolcaTech/cryptoxmas.xyz#34]
**Fix**
 - [x] "Powered by Volca" is above titile:

![image 2018-12-04 14 31 46](https://user-images.githubusercontent.com/6490508/49439326-caf3c900-f7d1-11e8-9cd2-805140b7ac1c.jpg)

 - [x] No link to "doesn’t need a crypto wallet" and no popup by clicking link:
(in figma: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Christmas-NFTs?node-id=112%3A0)

![image 2018-12-04 14 38 36](https://user-images.githubusercontent.com/6490508/49439517-4ce3f200-f7d2-11e8-9d40-06d70ae091d7.jpg)

 - [x] Add popup by clicking link "will be sent to charity"
(in figma: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Christmas-NFTs?node-id=406%3A1)

@seichris please provide text for popup

![image 2018-12-04 14 31 59](https://user-images.githubusercontent.com/6490508/49439611-98969b80-f7d2-11e8-9ada-343aa4dd9665.jpg)

**Add**

 - [x] Text after NFT image: "Details on Etherscan"
(in figma: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Christmas-NFTs?node-id=126%3A526)

![screenshot 2018-12-04 at 14 44 17](https://user-images.githubusercontent.com/6490508/49439814-19ee2e00-f7d3-11e8-9e92-4ac5a10cd66a.png)

**Comment by artyomignatyev** [comment]
Looks good, thanks

@sashamihaha, frame in figma: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Christmas-NFTs?node-id=406%3A1

**Comment by artyomignatyev** [comment]
- [ ] Raise the image (GIF) above gray text
- [ ] Gray text align a little bit right
(frame in firgma: https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Crypto-Xmas?node-id=114%3A559)

![processing](https://user-images.githubusercontent.com/6490508/49480165-b564ba80-f836-11e8-8a90-72d4a4594540.png)

**Comment by Kisgus** [comment]
Is this fixed yet guys or should I leave it open?

**Comment by sashamihaha** [comment]
> Is this fixed yet guys or should I leave it open?

Not yet. I don't have the footer bug on any of my devices, and I can't reproduce it to fix. Guess this bug only appears on iPhone.

**Comment by sashamihaha** [comment]
fixes done
