### ISSUE TITLE
Update charts on README.md

### ISSUE THREAD

**Issue by Dobrokhvalov** [VolcaTech/cryptoxmas.xyz#35]
Current charts on Readme page are not vaild. @seichris or @artyomignatyev please provide the nice designed charts for buying and claiming gift flow.  

![2018-12-04 15 20 44](https://user-images.githubusercontent.com/4770810/49441673-4f494a80-f7d8-11e8-83aa-aea16e5f674e.jpg)
![2018-12-04 15 20 40](https://user-images.githubusercontent.com/4770810/49441674-4fe1e100-f7d8-11e8-9fe1-2a3b70f6982e.jpg)

**Comment by artyomignatyev** [comment]
I'll work on that today

**Comment by Dobrokhvalov** [comment]
@artyomignatyev The charts need to be updated as we moving donation proceeds from buy to claim. 

- [ ] remove Giveth campaign from Buy flow (point 3) 
- [ ] new Claim flow in the image below 

![claim](https://user-images.githubusercontent.com/4770810/49450381-ea005400-f7ed-11e8-9b1a-1574b2f1242e.jpg)

**Comment by artyomignatyev** [comment]
![buy flow](https://user-images.githubusercontent.com/6490508/49478109-f73e3280-f82f-11e8-8b4e-dd768b3a58ab.png)

![claim flow](https://user-images.githubusercontent.com/6490508/49478114-fc9b7d00-f82f-11e8-8051-903e90635c9f.png)
