### ISSUE TITLE
Group NFTs per Dapp

### ISSUE THREAD

**Issue by Dobrokhvalov** [VolcaTech/cryptoxmas.xyz#45]
DApps can provide their tokens to join our campaign. We need to group NFTs accordingly.

**Comment by seichris** [comment]
Its an interesting question governance-wise. We could put new submissions on top, or sort them differently. And implement a filter in the frontend.

**Comment by Dobrokhvalov** [comment]
Closing is we don't have a lot of partner tokens and decided to group tokens by price/uniqueness category. Will be implemented in #44
