### ISSUE TITLE
Implement integration with Giveth

### ISSUE THREAD

**Issue by Kisgus** [VolcaTech/cryptoxmas.xyz#5]

**Comment by seichris** [comment]
### The To Do's

- [ ] Who do we give the money?
- [ ] Milestones
- [ ] Giveth campaign description https://github.com/VolcaTech/cryptoxmas.xyz/issues/9
- [ ] Campaign picture
- [ ] Set campaign manager
- [ ] Someone to propose mile stones
- [ ] Someone then submit the milestone
- [ ] Someone to review milestones
- [ ] Set on a chat software. Set up a chat & people to help in the chat
- [ ] ...?

**Comment by Kisgus** [comment]
I intended this to be only around the technical integration. The campaign itself, coms etc. I imagined to have in #9

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/VolcaTech/cryptoxmas.xyz/pull/57
