### ISSUE TITLE
Landing page v1

### ISSUE THREAD

**Issue by Kisgus** [VolcaTech/cryptoxmas.xyz#7]
Will up it to https://seichris.github.io/santa-landingpage/

## Design

https://www.figma.com/file/YcB7MJacjZGxnbkgIpqCkkUe/Christmas-NFTs?node-id=218%3A929

### The Problem

You want to introduce crypto to your friends - crypto and what it means to you (community, the fun building new stuff, working with lots of different ppl on one world computer...)

### The Solution

Gift crypto. Send it per Link, without the usual onboarding hazzle

### How it Works

- Buy a NFT. All donations go to charity
- Add some Ether, for your friend
- Send it - simply via text message
- That’s it. Your friend is set up to explore the web3

**Comment by seichris** [comment]
Site is in a state which can be shown to the outside world. https://seichris.github.io/santa-landingpage/

ToDo:

- [ ] Set the DNS to cryptoxmas.xyz
- [ ] Link to a public telegram chat for crypto projects
- [ ] Put in some more pictures, once we got NFTs

**Comment by seichris** [comment]
More ToDos:

- [ ] Modify logos
- [ ] Change that one big image
- [ ] Add footer
- [ ] Link medium

**Comment by seichris** [comment]
- [ ] logos 1.5x smaller
- [ ] header not sticky
- [ ] header logo same size as in dapp
- [ ] die links soll man sehen und auf mobile auch in weiss
- [ ] social links on mobile
 --------
- [ ] dapp desktop ready
