### ISSUE TITLE
Write up giveth campaign description

### ISSUE THREAD

**Issue by Kisgus** [VolcaTech/cryptoxmas.xyz#9]

**Comment by seichris** [comment]
### The To Do's

- [ ] Who do we give the money?
- [ ] Milestones
- [ ] Giveth campaign description https://github.com/VolcaTech/cryptoxmas.xyz/issues/9
- [ ] Campaign picture
- [ ] Set campaign manager
- [ ] Someone to propose mile stones
- [ ] Someone then submit the milestone
- [ ] Someone to review milestones
- [ ] Set on a chat software. Set up a chat & people to help in the chat
- [ ] ...?

**Comment by seichris** [comment]
It would be cool to sort Donations by price, to see a hall of fame, with the highest donors.
